# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://vignesh-narayanaswamy.github.io/camsdk/"

git_url = "https://github.com/vignesh-narayanaswamy/camsdk/tree/master/"

def custom_doc_links(name): return None
